### ISSUE TITLE
Severe performance regression

### ISSUE THREAD

**Issue by dennwc** [direct-connect/go-dc#9]
As expected, the latest changes from https://github.com/direct-connect/go-dc/pull/8 lead to severe performance regression:

```
benchmark             old ns/op     new ns/op     delta
BenchmarkReader-4     13904844      93300098      +570.99%

benchmark             old allocs     new allocs     delta
BenchmarkReader-4     6              7              +16.67%

benchmark             old bytes     new bytes     delta
BenchmarkReader-4     4950          35372         +614.59%
```
So it's ~6 times slower and allocates ~6 times more.

It should be fixed before we tag a new version.

CC @gswly

(updated to use the same max message size as before)

**Comment by aler9** [comment]
Sorry about that, but zlib support had to be added in order to create a common library.
A solution consists in taking the previous code and use it to create a "fast" buffered reader, then replace bufio.Reader with this fast reader and see if this improves things.

Unfortunately i have a high-priority work to finish, but if you share the source of the benchmark i'd be happy to work on in when i have spare moment again.

**Comment by dennwc** [comment]
No worries, I will try to fix it today.
